/**
 * Node ids.
 *
 * The id is what a human reads in a diff and what the repair loop prints, so it
 * should say something. Figma layer names are the only available source and
 * they are mostly noise — 58% of the photos page and 74% of the fixture card
 * are `Frame 427320816`, `Ellipse 13`, `Vector`.
 *
 * So: use the name when it carries information, fall back to the node type
 * when it does not, and never let two nodes collide. Deterministic in both
 * cases — same IR in, same ids out, which is what makes a regenerated tree
 * diffable against the last one.
 */

import type { FrameIRNode } from "@fanos/surface-canvas/ir";

/** Figma's autogenerated names, which tell you nothing about the design. */
const GENERIC =
  /^(frame|group|rectangle|ellipse|vector|union|subtract|intersect|exclude|component|instance|line|star|polygon|image|mask|clip|shape|path|layer)([\s_-]*\d+)*$/i;

/**
 * SVG-import scaffolding: "Clip path group", "clip0_160_1336", "Mask group".
 *
 * Multi-word, so `GENERIC` — which anchors on a single token — lets them
 * through as if they meant something. They do not: pasting an SVG logo into
 * Figma produces a clip wrapper around the real artwork, and naming a glyph
 * after it buries the one layer that identifies the thing. Four club crests
 * came out as `clip_path_group`.
 */
const STRUCTURAL = /^(clip|mask)([\s_-]*(path|group))+([\s_-]*\d+)*$|^clip\d+[\d_]*$/i;

const MAX = 40;

export function slug(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, MAX)
    .replace(/_+$/g, "");
}

/** Does this layer name carry meaning, or is it Figma's default? */
export function isMeaningful(name: string): boolean {
  const trimmed = name.trim();
  if (trimmed === "") return false;
  if (GENERIC.test(trimmed)) return false;
  if (STRUCTURAL.test(trimmed)) return false;
  // A pure number or punctuation run is no more useful than "Frame 12".
  return /[a-z]/i.test(trimmed);
}

/**
 * Assign ids across a whole tree, in traversal order.
 *
 * Collisions get a numeric suffix rather than a hash: `stat_10` and `stat_10_2`
 * survive a re-run and read as what they are, where a hash would churn on every
 * regeneration and defeat diffing.
 */
export class IdAllocator {
  private readonly used = new Set<string>();

  take(node: FrameIRNode, fallbackType: string): string {
    const base = isMeaningful(node.name) ? slug(node.name) : slug(fallbackType);
    const root = base === "" ? "node" : base;
    if (!this.used.has(root)) {
      this.used.add(root);
      return root;
    }
    for (let i = 2; ; i++) {
      const candidate = `${root}_${i}`;
      if (!this.used.has(candidate)) {
        this.used.add(candidate);
        return candidate;
      }
    }
  }

  /** Reserve an id built by the caller (synthetic nodes). */
  reserve(preferred: string): string {
    if (!this.used.has(preferred)) {
      this.used.add(preferred);
      return preferred;
    }
    for (let i = 2; ; i++) {
      const candidate = `${preferred}_${i}`;
      if (!this.used.has(candidate)) {
        this.used.add(candidate);
        return candidate;
      }
    }
  }
}
